/** Static fixtures for the Plan Your Year marketing demo. */
export const PLAN_YOUR_YEAR_DEMO = {
  labels: {
    workspace: "Calendar",
    school: "Edmondson Elementary",
    month: "August 2026",
    importReview: "Import / Review",
  },
  views: ["Month", "Week", "Agenda"] as const,
  activeView: "Month" as const,
  layers: [
    { id: "events", label: "Events", active: true },
    { id: "scheduled", label: "Scheduled posts", active: true },
    { id: "published", label: "Published", active: true },
  ] as const,
  weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const,
  /** Four weeks of August — fits the Features demo frame. */
  days: [
    { key: "d2", date: 2, weekday: 0 },
    { key: "d3", date: 3, weekday: 1 },
    { key: "d4", date: 4, weekday: 2 },
    { key: "d5", date: 5, weekday: 3 },
    { key: "d6", date: 6, weekday: 4 },
    { key: "d7", date: 7, weekday: 5 },
    { key: "d8", date: 8, weekday: 6 },
    { key: "d9", date: 9, weekday: 0 },
    { key: "d10", date: 10, weekday: 1 },
    { key: "d11", date: 11, weekday: 2 },
    { key: "d12", date: 12, weekday: 3 },
    { key: "d13", date: 13, weekday: 4 },
    { key: "d14", date: 14, weekday: 5 },
    { key: "d15", date: 15, weekday: 6 },
    { key: "d16", date: 16, weekday: 0 },
    { key: "d17", date: 17, weekday: 1 },
    { key: "d18", date: 18, weekday: 2 },
    { key: "d19", date: 19, weekday: 3 },
    { key: "d20", date: 20, weekday: 4 },
    { key: "d21", date: 21, weekday: 5 },
    { key: "d22", date: 22, weekday: 6 },
    { key: "d23", date: 23, weekday: 0 },
    { key: "d24", date: 24, weekday: 1 },
    { key: "d25", date: 25, weekday: 2 },
    { key: "d26", date: 26, weekday: 3 },
    { key: "d27", date: 27, weekday: 4 },
    { key: "d28", date: 28, weekday: 5 },
    { key: "d29", date: 29, weekday: 6 },
  ],
  /** Scheduled Meta post drag-rescheduled Wed Aug 5 → Fri Aug 7 */
  dragPost: {
    id: "save-the-date",
    kind: "post" as const,
    category: "Social",
    title: "Save the Date",
    status: "Scheduled" as const,
    platforms: ["fb", "ig"] as const,
    fromDay: "d5",
    toDay: "d7",
  },
  /** Event opened after the drag */
  openEvent: {
    id: "bts-fair",
    kind: "event" as const,
    category: "EVENT",
    title: "Back to School Fair",
    status: "Draft" as const,
    day: "d5",
  },
  staticCards: [
    {
      id: "spirit",
      day: "d4",
      kind: "post" as const,
      category: "Social",
      title: "Spirit Afternoon",
      status: "Published" as const,
      platforms: ["fb", "ig"] as const,
    },
    {
      id: "mixer",
      day: "d12",
      kind: "event" as const,
      category: "EVENT",
      title: "Kindergarten Mixer",
      status: "Draft" as const,
    },
    {
      id: "volunteer",
      day: "d19",
      kind: "post" as const,
      category: "Social",
      title: "Volunteer Call",
      status: "Scheduled" as const,
      platforms: ["fb"] as const,
    },
  ],
  eventDetail: {
    eyebrow: "Event",
    title: "Back to School Fair",
    dateLine: "August 5 · 3:00–4:30 PM",
    location: "Edmondson Elementary",
    status: "Draft",
    summary:
      "Welcome families back with booths, teacher meet-and-greets, and a calm first look at the school year.",
    planItems: [
      { label: "Save the Date", timing: "3 weeks before", state: "Scheduled" },
      { label: "Volunteer roles", timing: "2 weeks before", state: "Needs help" },
      { label: "Final Reminder", timing: "3 days before", state: "Draft" },
      { label: "Event Day posts", timing: "Day of", state: "Not started" },
    ],
    notes: [
      "Confirm gym + outdoor booth layout with the office.",
      "Share flyer artwork with the approvals queue.",
      "Add bilingual caption variants before publish.",
    ],
    hubCta: "Open Planning Hub",
  },
  toast: {
    title: "Planning Hub open",
    description: "Jump into communications for this event.",
  },
} as const;
